TIPO_MINUTA = 'Tipo da minuta da receita em questão'
CODIGO_RECEITA = 'Código relacionado a descrição da receita'
DESCRICAO_RECEITA = 'Recursos auferidos na gestão, a serem computados na apuração do resultado do exercício, desdobrados nas categorias econômicas de correntes e de capital.'
FONTE_RECURSO = 'Identifica as fontes de financiamento dos gastos públicos. As fontes/destinações de recursos reúnem certas Naturezas de Receita conforme regras previamente estabelecidas. Por meio do orçamento público, essas fontes/destinações são associadas a determinadas despesas de forma a evidenciar os meios para atingir os objetivos públicos.'
CO_TCE = 'O CO TCE (Código de Acompanhamento da Execução Orçamentária do Tribunal de Contas do Estado) é um código alfanumérico atribuído pelo Tribunal de Contas do Estado a cada unidade orçamentária e ação governamental executada pelos órgãos públicos estaduais.'
CO_AUX = 'O CO AUX (Código de Acompanhamento da Execução Orçamentária Auxiliar) é um código alfanumérico utilizado pelos contadores para ajudar na gestão da execução orçamentária.'
HISTORICO = 'Observações da receita em questão'
VALOR = 'Valor da receita'
MUNICIPIO = 'Município de origem da receita'
DATA = 'Data da receita'


NUMERO_EMPENHO = 'Identificação de uma despesa para um ano específico'
ANO_DESPESA = 'Ano associado ao registro da despesa'
TIPO_DESPESA = 'O Tipo de Despesa é uma das informações que compõem a estrutura do Plano de Contas aplicável ao setor público. Essa estrutura é formada por um conjunto de contas contábeis que agrupam as informações financeiras relacionadas às transações realizadas pelo governo. Entre as categorias mais comuns de Tipo de Despesa estão as despesas com pessoal, com materiais e serviços, com investimentos e com juros e encargos da dívida pública.'
DATA_EMPENHO = 'A data de empenho corresponde ao momento em que o órgão público faz o comprometimento de uma determinada despesa, ou seja, é o registro do valor que será utilizado para pagamento de um serviço ou produto. Essa data é importante porque permite acompanhar a execução dos gastos públicos e verificar se as despesas estão sendo realizadas de acordo com as prioridades estabelecidas pelo governo.'
DATA_LIQUIDACAO = 'A data de liquidação corresponde ao momento em que o órgão público atesta o recebimento do bem ou serviço adquirido, verificando se a entrega ou prestação do serviço foi feita conforme o previsto no contrato ou acordo. Essa verificação é importante para garantir que o dinheiro público está sendo utilizado de forma adequada e que o serviço ou produto adquirido é de qualidade.'
DATA_PAGAMENTO = 'A data de pagamento corresponde ao momento em que o órgão público realiza a efetivação do pagamento da despesa. É importante que essa data seja divulgada para que a sociedade possa acompanhar o cumprimento das obrigações financeiras do governo, bem como verificar se os pagamentos estão sendo realizados dentro do prazo estabelecido em lei.'
UNIDADE = 'É a repartição da Administração a quem o orçamento do Município consigna dotações específicas para a realização de seus programas de trabalho.'
FUNCAO = 'Representa o maior nível de agregação das diversas áreas de despesa que competem ao setor público. A função quase sempre se relaciona com a missão institucional do órgão, por exemplo, cultura, educação, saúde, defesa, dentre outras'
SUBFUNCAO = 'A subfunção representa um nível de agregação imediatamente inferior à função e deve evidenciar cada área da atuação governamental, por intermédio da agregação de determinado subconjunto de despesas e identificação da natureza básica das ações que se aglutinam em torno das funções.'
PROGRAMA = 'Programa é o instrumento de organização da atuação governamental que articula um conjunto de ações que concorrem para a concretização de um objetivo comum preestabelecido, visando à solução de um problema ou ao atendimento de determinada necessidade ou demanda da sociedade.'
ATIVIDADE = 'A atividade é o instrumento de programação que visa à realização de determinado fim ou objetivo de governo, envolvendo um conjunto de operações que se realizam de modo contínuo e que concorrem para a concretização de um objetivo.'
CATEGORIA_ECONOMICA = 'A Categoria Econômica é uma classificação, tanto da receita quanto da despesa, que visa propiciar elementos para uma avaliação do efeito econômico das transações do setor público. Quanto à categoria econômica, os §§ 1o e 2o do art. 11 da Lei no 4.320, de 1964, classificam as receitas orçamentárias em Receitas Correntes (código 1) e Receitas de Capital (código 2): 1 - Receitas Correntes: são arrecadadas dentro do exercício, aumentam as disponibilidades financeiras do Estado, em geral com efeito positivo sobre o Patrimônio Líquido, e constituem instrumento para financiar os objetivos definidos nos programas e ações correspondentes às políticas públicas. 2 - Receitas de Capital: aumentam as disponibilidades financeiras do Estado. Porém, de forma diversa das Receitas Correntes, as Receitas de Capital não provocam efeito sobre o Patrimônio Líquido. A despesa, assim como a receita, é classificada em duas categorias econômicas, com os seguintes códigos: 3 - Despesas Correntes: as que não contribuem, diretamente, para a formação ou aquisição de um bem de capital. 4 - Despesas de Capital: as que contribuem, diretamente, para a formação ou aquisição de um bem de capital.'
VALOR_DESPESA = 'Valor da despesa'
BENEFICIARIO = 'Entidades, pessoas ou empresas com os quais o órgão e/ou autarquia contrai dívidas.'
CPF_CNPJ = 'CPF ou CNPJ do beneficiário'
HISTORICO_DESPESA = 'Descrição da despesa'
MUNICIPIO_DESPESA = 'Município de origem da despesa'

ITEM_DESPESA = 'Numeração do item na despesa relacioanda'
NUMERO_DESPESA_ITEM = 'Número da despesa relacionada ao item'
COMPLEMENTO_ITEM_DESPESA = 'Informações adicionais sobre o item da despesa'
UNIDADE_ITEM = 'Unidade de medida do item da despesa'
MARCA_ITEM = 'Marca do item da despesa'
QUANTIDADE_ITEM = 'Quantidade de itens'
VALOR_UNITARIO_ITEM = 'Valor unitário do item'
VALOR_TOTAL_ITEM = 'Valor total do item'

NUMERO_DESPESA_NF = 'Número da despesa relacionada à fatura'
ANO_DESPESA_NF = 'Ano da despesa relacionada à fatura'
MUNICIPIO_NF = 'Município de origem da despesa relacionada à fatura'
CODIGO_NF = 'Código da fatura'
TIPO_NF = 'Tipo da fatura'
NOTA_FISCAL = 'Número da nota fiscal'
SERIE_NF = 'Série da nota fiscal'
DATA_EMISSAO_NF = 'Data de emissão da nota fiscal'
DATA_VENCIMENTO_NF = 'Data de vencimento da nota fiscal'
CHAVE_ACESSO_NF = 'Chave de acesso da nota fiscal'


PAGE = 'Define qual página de dados você deseja acessar. A paginação é geralmente feita de forma sequencial, onde a primeira página contém o primeiro "bloco" de dados, a segunda página contém o segundo "bloco", e assim por diante.'
PAGE_SIZE = 'Define o número de itens que você quer obter por página. Esse parâmetro controla quantos resultados serão retornados em cada "página" de dados.'